### ISSUE TITLE
support arbitrary image size?

### ISSUE THREAD

**Issue by foobarhe** [Sxela/ArcaneGAN#17]
Great work!

The unet prediction result will be cropped to be the same size as the training input, e.g. 256 or 512. 
For arbitrary image size (e.g. 1280*720), how to config or set the model to output the same size of the input image as your colab did? 
Thank you.

**Comment by seawater668** [comment]
@Sxela 
Must the length and width of the input image remain the same, otherwise an error will be reported, the input of any image is not supported, and the output cannot be kept consistent with the input？
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 430 but got size 429 for tensor number 1 in the list.
